create extension if not exists pgcrypto;

create table if not exists venues (id uuid primary key default gen_random_uuid(), name text not null unique, kind text not null, enabled boolean not null default false, created_at timestamptz not null default now());
create table if not exists networks (id uuid primary key default gen_random_uuid(), name text not null unique, chain_id bigint, rpc_url text, enabled boolean not null default false, created_at timestamptz not null default now());
create table if not exists tokens (id uuid primary key default gen_random_uuid(), network_id uuid references networks(id), symbol text not null, address text, decimals integer, is_stable boolean not null default false, created_at timestamptz not null default now(), unique(network_id,address));
create table if not exists markets (id uuid primary key default gen_random_uuid(), venue_id uuid references venues(id), network_id uuid references networks(id), base_token_id uuid references tokens(id), quote_token_id uuid references tokens(id), symbol text not null, enabled boolean not null default true, unique(venue_id,network_id,symbol));
create table if not exists opportunities (id uuid primary key default gen_random_uuid(), correlation_id uuid not null default gen_random_uuid(), symbol text not null, buy_venue text not null, sell_venue text not null, buy_network text, sell_network text, quantity numeric not null, gross_profit numeric not null, total_cost numeric not null, safety_reserve numeric not null, net_profit numeric not null, net_profit_pct numeric not null, status text not null, quote_timestamp timestamptz not null, expires_at timestamptz not null, created_at timestamptz not null default now());
create table if not exists orders (id uuid primary key default gen_random_uuid(), correlation_id uuid not null, venue text not null, symbol text not null, side text not null, status text not null, quantity numeric not null, filled_quantity numeric not null default 0, average_price numeric, fee numeric, external_order_id text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists trade_reconciliations (id uuid primary key default gen_random_uuid(), correlation_id uuid not null, status text not null, realized_pnl numeric, details jsonb not null default '{}', created_at timestamptz not null default now());
create table if not exists capital_events (id uuid primary key default gen_random_uuid(), correlation_id uuid, source text not null, amount numeric not null, asset text not null, status text not null, created_at timestamptz not null default now());
create table if not exists risk_events (id uuid primary key default gen_random_uuid(), correlation_id uuid, severity text not null, code text not null, message text not null, created_at timestamptz not null default now());
create table if not exists audit_logs (id uuid primary key default gen_random_uuid(), correlation_id uuid, actor text, action text not null, details jsonb not null default '{}', created_at timestamptz not null default now());
